### ISSUE TITLE
Cannot connect to the virtual machine in VMWare

### ISSUE THREAD

**Issue by Tilie** [johnboiles/obs-mac-virtualcam#141]
Vmware can recognize the camera when  virtual machine is turned off, but when I turn  virtual machine  on
vmware shows me a message that “Disconnect the virtual camera from the virtual machine”
**To Reproduce**
Connect a virtual camera in the panel
Turn on the virtual machine

**Expected behavior**
The virtual camera is normally connected to the virtual machine

**Desktop (please complete the following information):**
 - OS version:  macOS Catalina 10.15.4
 - Application: VMware
 - Virtualcam version:  1.1.0
 - OBS version: 25.0.8

**Additional context**
I know this request is a bit excessive because it is not like a bug but a new feature

**Comment by gxalpha** [comment]
Have you tried the resigning and stuff? ([Click here](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins))
May have something to do with that, although I can't tell at the moment because we had no one with this issue so far.

Could you take a look at Console.app and check for any reports with `OBSDAL` when starting the camera?

**Comment by Tilie** [comment]
thank you for your reply
On Console.app I saw "OBSDAL: Queue is full, bailing out",
I don't know if this is a normal phenomenon

“sudo codesign”is work with other app but does not work for vmware,
Look at the past is not caused by the same reason

**Comment by johnboiles** [comment]
Oh interesting so VMWare has the ability to expose cameras from the host computer as devices in the virtual machines?

`Queue is full, bailing out` happens if for some reason the host app has started the stream but is not reading the frames. Hard to say why VMWare isn't consuming frames.

**Comment by Tilie** [comment]
VMWare's [documentation](https://docs.vmware.com/en/VMware-Fusion/11/com.vmware.fusion.using.doc/GUID-CA34C957-66BB-45FB-B4BC-DB7C6868327D.html) about adding cameras
In fact, VMWare has indeed started the stream, when doing the same as in the documentation
.At this time VMWare can see the preview camera screen.But I try to open the virtual machine, then message box appeared telling me "The virtual video camera cannot connect to the virtual machine."I guess this is why VMWare refuses to connect

**Comment by moo-im-a-cow** [comment]
i have been trying the same thing, except i tried while the vm is running.

in the add hardware page, choose camera, then choose "obs virtual camera", 
the preview shows for a split second, then it goes back to the "existing hardware page"

it works in parallels desktop (another vm program) but that only has the option to "share mac camera" which shares all cameras from the host (dont want to share the real camera with the virtual machine)

**Comment by johnboiles** [comment]
Maybe dump all the `OBSDAL` Console.app logs would be the next step here and any other VMware logs that look relevant

**Comment by Tilie** [comment]
This is what I got from Console.app
[log.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4688567/log.txt)
I don't know how to get VMware logs

**Comment by johnboiles** [comment]
Hmm nothing looks out of sorts in that log until the `Queue is full, bailing out` message that indicates VMWare is not reading frames.

Can you try downloading the latest [release](https://github.com/johnboiles/obs-mac-virtualcam/releases/tag/v1.1.2)? It changed the way it reports timestamps for frames.. _maybe_ it will help

**Comment by johnboiles** [comment]
One thing that's a little bit weird is that `HardwarePlugIn_DeviceStopStream` is called right before `HardwarePlugIn_StreamCopyBufferQueue`. Those are external calls to the plugin though and would be initiated by VMWare. Not sure why that would be the case.

**Comment by johnboiles** [comment]
I also see that it's trying to set `kCMIOStreamPropertyFormatDescription` and `kCMIOStreamPropertyFrameRate` instead of just consuming whatever we get it. What framerate/resolution are you using in OBS? If you're not already maybe try a standard resolutions and framerate like 1280x720 and 30fps

**Comment by Tilie** [comment]
I deleted the old extension and installed the new one. Set the resolution and frame rate of 1280x720 and 30fps.But this does not work

**Comment by Tilie** [comment]
I am now trying to collect VMware logs,But I cannot confirm whether it will contain the required information

**Comment by johnboiles** [comment]
Yeah who knows but it's worth a shot!

**Comment by Tilie** [comment]
I got the log But it is too big to upload directly to this conversation

**Comment by Tilie** [comment]
The file has 353MB.How can i pass the file to you

**Comment by johnboiles** [comment]
Omg is that a text log? That's crazy big. If it's text maybe just send the last 10000 lines (either edit in a text editor or use a command line tool like `tail`). If it's not text I don't know how I would read it.

**Comment by Tilie** [comment]
This file was created by VMware. I tried to unzip it. It is indeed a text file. Among the many files is a 4.1GB file named "system.log". I think this file is the culprit.

**Comment by Tilie** [comment]
[log.txt](https://github.com/johnboiles/obs-mac-virtualcam/files/4689998/log.txt)
This text is the last 10000 line file of 4.1GB

**Comment by Tilie** [comment]
[VMware Fusion Problem Report 2020-05-27 at 23.21.14.zip](https://github.com/johnboiles/obs-mac-virtualcam/files/4690013/VMware.Fusion.Problem.Report.2020-05-27.at.23.21.14.zip)
Recompressed files

**Comment by johnboiles** [comment]
There's a lot going on there. Yeah the system.log is usually the same thing you get in Console.app. Not seeing anything immediately obvious but just scanned really quick. Feel free to look through those files for mentions of `CMIO` `obs-mac-virtualcam` `Framerate` `FPS` `Resolution` `Camera`, etc

**Comment by moo-im-a-cow** [comment]
so i think i have a bit of progress

in the newest version of VMware fusion (11.5.5 (16269456)) (downloaded from the website today), 

it seems to have a similar problem to all the other programs with the library verification, but with a few differences

using a variation of this comment's command: https://github.com/johnboiles/obs-mac-virtualcam/issues/4#issuecomment-612568927, modified to work with spaces in the name, and 
`APPLICATION="/Applications/VMware Fusion.app" && codesign -d --entitlements :- "$APPLICATION" > entitlements.xml && sudo codesign --sign - "$APPLICATION" --force --preserve-metadata=identifier,resource-rules,flags --entitlements=entitlements.xml && rm entitlements.xml`
this shouldnt actually modify the entitlements, only resign with same entitlements.

signing finishes successfully, but vmware fusion crashes with `Namespace CODESIGNING, Code 0x1` (from the "do you want to report to apple-> report", in the big text box)
this has the same result whether i modify entitlements.xml or not.

however, if i run `sudo codesign --force --deep --sign - /Applications/VMware\ Fusion.app` (finished product has no entitlements), vmware fusion will open, and you can successfully add the camera to the vm, and can preview it in the "add camera" window, BUT the virtual machine wont start
<img width="1836" alt="Screen Shot 2020-06-01 at 1 41 32 pm" src="https://user-images.githubusercontent.com/5210502/83374865-3ee74f80-a410-11ea-8cf7-43cfe0a29494.png">



i have been opening fusion through terminal, have seen 2 noteworthy errors in terminal:

right on startup: `2020-06-01T13:46:46.495| PrivilegedHelper: Failed to verify the code signature of /Applications/VMware Fusion.app/Contents/Frameworks/libpng12.0.dylib due to` (thats all thats there, `to` is the last word, i copied the whole message)
i have tried running codesign on libpng12.0.dylib directly, and i have tried an original/untouched version of everything in the Frameworks folder, has had no effect


and then when you try to start the virtual machine: `SSLLoadSharedLibraries: Failed to load OpenSSL libraries. libdir is /dev/null/Non-existing DEFAULT_LIBDIRECTORY`
<img width="761" alt="Screen Shot 2020-06-01 at 1 41 50 pm" src="https://user-images.githubusercontent.com/5210502/83377162-1bc09e00-a418-11ea-8341-80e94de27fa2.png">

this happens even when the camera is not added to the VM

it also shows a bunch of `2020-06-01 13:46:46.897 VMware Fusion[63311:312894] OBSDAL: HardwarePlugIn_ObjectIsPropertySettable Device(33) kCMIODevicePropertyDeviceMaster self=0x1137f2d50 settable=1` messages


i have the latest version of obs-mac-virtualcam, but i built it from source, signed with a free apple developer account, only change is the device name that shows up in programs

Fusion's default entitlements includes "com.apple.security.cs.disable-library-validation" set to "false"

sorry this comment is so unorganised, but i hope it is helpful
i think its just a matter of getting fusion and its libraries signed correctly

can anyone else try with the latest version of fusion

**Comment by ilsalvopss** [comment]
I'm pretty new to the field but it seems that vmware tries to call `hasPropertyWithAddress` and `setPropertyDataWithAddress` passing cases not handled in the switch in `Device.mm`. Could that be a problem?

here the log clearly states the message generated by the default case:
<img width="1391" alt="Schermata 2020-06-04 alle 13 09 19" src="https://user-images.githubusercontent.com/25132980/83750135-215ef380-a665-11ea-9de1-03cdf3dbef43.png">

<img width="953" alt="Schermata 2020-06-04 alle 13 09 45" src="https://user-images.githubusercontent.com/25132980/83750170-3045a600-a665-11ea-86d0-201cda33798c.png">

**Comment by johnboiles** [comment]
This seems like Fusion just doesn't support virtual cameras fully. Closing this as virtual camera development is moving to the OBS repo
