### ISSUE TITLE
[Feature Request] Upload Test Card .pcvd file for public edits

### ISSUE THREAD

**Issue by Joel4763** [johnboiles/obs-mac-virtualcam#168]
Other issues have talked about maybe removing the text on the Test Card, and others wanting localization.

I want the .pcvd file uploaded so it can then be tweaked, and re-exported as a png, not as code; As needing to draw it onto the "virtual canvas" is unnecessary and a simple png can be instantly rendered onto it.

As with localizations, I was going to change the text to simple "Universal Symbols" like "L" and "R" for the text, and with it mirrored, it would then be backwards "R" and backwards "L".

**Comment by gxalpha** [comment]
I think you should better put your thoughts on this in #154 so that we don't have 2 separate discussions about the same thing.

**Comment by johnboiles** [comment]
Just uploaded the test card in https://github.com/johnboiles/obs-mac-virtualcam/commit/240eb362e5154500636aaae0eab14c455bf25e12

As for exporting as a png, that doesn't work since the resolution of the test card can be infinitely variable. Currently what happens is that the test card code will generate and cache the test card image at runtime at the proper resolution.

**Comment by Joel4763** [comment]
Ah, it also has a time sync on it, which is not static.

Thanks for uploading the project file!
