### ISSUE TITLE
[BUG] Silent Incompatibility with PTP Webcam

### ISSUE THREAD

**Issue by lupiter** [johnboiles/obs-mac-virtualcam#191]
_Attention: While Zoom says they re-enabled virtual cameras, only certain ones they whitelisted work. Currently, this plugin does not work with Zoom out of the box! See https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility#apps-dont-allow-dal-plugins for a workaround._

**Describe the bug**
When [PTP Webcam](https://github.com/dognotdog/ptpwebcam) and obs-mac-virtualcam are both installed, only PTP Webcam will work. In QuickTime, even when the Nikon camera is disconnected, the OBS virtual camera won't show as an input source. Deleting PTP Webcam restores obs-mac-virtualcam's functionality. I'm not sure whose bug this is as I don't have any logs.

**To Reproduce**
1. Install PTP Webcam as per it's instructions
2. Install OBS & obs-mac-vitualcam as per the install instructions
3. Open OBS and set up something (e.g. screen capture)
4. Start OBS virtual cam
5. Open QuickTime, select New Movie Recording

**Expected behavior**
OBS Virtual Camera is an available source (only built-in webcam, or PTP Webcam if connected)

**Desktop (please complete the following information):**
 - OS version: macOS Catalina 10.15.6
 - Application: QuickTime
 - Virtualcam version: tried both 1.2.0 and 1.1.2
 - OBS version: 25.0.8

Please let me know if I can provide any helpful logs! I'm also happy to file this with PTP Webcam - since PTP _is_ working, I'm assuming that obs-mac-virtualcam is the cause.

**Comment by johnboiles** [comment]
Looks like their code is (at least in part) based on this repo and they copied the unique UDID of this plugin instead of generating their own (see [their code](https://github.com/dognotdog/ptpwebcam/blob/master/PtpWebcamDalPlugin/Info.plist#L23) vs [my code](https://github.com/johnboiles/obs-mac-virtualcam/blob/master/src/dal-plugin/Info.plist#L27))

Would you mind opening an issue with that repo and requesting that they generate their own UDID?

**Comment by gxalpha** [comment]
Should be fixed (https://github.com/dognotdog/ptpwebcam/issues/29#issuecomment-668837567)

Please report back in case it isn't.

**Comment by dognotdog** [comment]
@johnboiles sorry for the mixup! This must have happened while I was trying to figure out the voodoo needed to actually get CoreMediaIO to request a stream from DAL plugin, which included a lot of Where's Waldo typo scrutinizing working code vs my code. Fixed in PTP Webcam [v1.0.0-beta2](https://github.com/dognotdog/ptpwebcam/releases/tag/v1.0.0-beta2).
