### ISSUE TITLE
[BUG] Not working with Microsoft Teams

### ISSUE THREAD

**Issue by loueu** [johnboiles/obs-mac-virtualcam#194]
Hi, pkg was seamlessly installed, opened OBS & Start Virtual Camera was there.
I tested it on Zoom and it works perfectly, however on Microsoft Teams it does not show up as an option for video camera.
Please help, thanks!

**Comment by chancedickson** [comment]
hi! this sounds like it is related to [this issue (#4)](https://github.com/johnboiles/obs-mac-virtualcam/issues/4). if you have an apple developer account, you can follow some instructions there to resign the app. otherwise, assuming you feel comfortable with letting Teams bypass some macOS security features, you can remove the signature from the app.

**Comment by gxalpha** [comment]
This is indeed not solvable by resigning the app, and we don't fully understand why.
There are some hanky workarounds in #172. Also please refer to that issue since most details of the problem can be found there.
