### ISSUE TITLE
[Support] Virtual Camera not showing up (DAL)

### ISSUE THREAD

**Issue by UConnPhysicsLabTech-ZT** [johnboiles/obs-mac-virtualcam#205]
**Describe the bug**
Virtual Camera feature does not work on macOS Big Sur

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Start Virtual Camera'
3. Try to load virtual camera in other software
4. Virtual Camera will not appear

**Expected behavior**
OBS Virtual Cam shows up as an option

**Desktop (please complete the following information):**
 - OS version: macOS Big Sur 11.0 Beta (20A5354i)
 - Application: Chrome, Zoom, WebEx
 - Virtualcam version: 1.2.0
 - OBS version: 25.0.8

**Comment by gxalpha** [comment]
This plugin generally works on Big Sur. I haven't tested 25 on Big Sur yet as I'm on 26-RC1 but your issue seems to be related to the part of the plugin that isn't dependent on OBS's version.
Please provide further information:
In the folder `/Library/CoreMediaIO/Plug-Ins/DAL` (go there via Finder -> Go to folder -> paste this): Is there a obs-mac-virtualcam.plugin file?
If yes, please open `Console.app`, search for `obs-mac-virtualcam` and check for logs appearing once you try to start up the camera (in QuickTime or Chrome for example)

**Comment by UConnPhysicsLabTech-ZT** [comment]
Hello Sebastian,

Thanks so much. I do see that plugin on my machine.

I followed your instructions as requested and pulled up the console for these actions. Please find the log attached here.

Thanks so much for working with me to fix this issue.

Best,
Za

ZAC TRANSPORT
LABORATORY TECHNICIAN
UCONN
DEPARTMENT OF PHYSICS, S207
196 AUDITORIUM ROAD, U-3046
STORRS, CT 06269-3046
PHONE: 860.486.0434
phys.uconn.edu<https://physics.uconn.edu/>

**Comment by gxalpha** [comment]
Hey @UConnPhysicsLabTech-ZT ,
I somehow cant see your log. If you've attached it to the email, maybe try clicking on the "view it on GitHub" and directly attaching it though a comment there

**Comment by UConnPhysicsLabTech-ZT** [comment]
> Hey @UConnPhysicsLabTech-ZT ,
> I somehow cant see your log. If you've attached it to the email, maybe try clicking on the "view it on GitHub" and directly attaching it though a comment there

Hello gxalpha, I realize that I didn't fully understand how the Virtual Camera works. I also see that the log file did not upload over email. I will attach it here.

[system.log](https://github.com/johnboiles/obs-mac-virtualcam/files/5189967/system.log)

 I am able to see the OBS Virtual Camera in the **web versions** of WebEx, Teams, and Google Chrome. However, the native applications for WebEx and Teams do not show the OBS Virtual Camera. Interestingly enough, the native Zoom application does recognize the OBS Virtual Camera.

**Comment by gxalpha** [comment]
@UConnPhysicsLabTech-ZT the problem is that some apps are afraid of allowing access to virtual cameras as they have too many rights and might become security risks.
Chrome and Zoom have solved that issue, WebEx and Teams have just disabled them, but you can re-enable them. For that, check [the wiki page on compatibility](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility). That should solve the issue, keep in mind said security risks (if this is your work pc check with your system admin).

**Comment by hiddenrebel** [comment]
I also got this error, the virtual camera does not appear in google meet. 
but after I update Chrome and re-launch it, the virtual camera appears on the option. (*with fliped window - this will be another case)

**Comment by johnboiles** [comment]
Ok sounds like this is a duplicate of the other tickets about WebEx and Teams.

@hiddenrebel most video conferencing software flips your webcam for previewing. Some have an option to disable that.
