### ISSUE TITLE
[Feature Request] Possibility to control the virtual camera remotely

### ISSUE THREAD

**Issue by dAnjou** [johnboiles/obs-mac-virtualcam#252]
**Is your feature request related to a problem? Please describe.**
Similar to #132 it'd be nice to toggle the camera remotely.

**Describe the solution you'd like**
I'd like to remote control the camera using tools like obs-cli or web-based tools.

**Describe alternatives you've considered (if applicable)**
While writing this I had the idea that toggling the camera could be done by simply switching to another scene. This workaround could also satisfy #189.

---

So, I guess depending on what is easier or quicker to implement, I'd be happy and thankful about either :)

**Comment by gxalpha** [comment]
As soon as OBS 26.1 is released, with this plugin built in, I'm sure obs-cli, obs-websocket etc will add the functionality.
Implementing all of this as part of the plugin would be overkill, so I'll close this. But since OBS 26.1 already has two release candidates, it can't be that far into the future until all of this is possible.
