### ISSUE TITLE
Build with Browser Plugin

### ISSUE THREAD

**Issue by techmaurice** [johnboiles/obs-mac-virtualcam#27]
It builds and works perfectly (Mac OSX 10.14.6 (18G4032)), but Browser Plugin is missing unfortunately.

I have tried installing the Browser Plugin separately, but to no avail.
When I start the official OBS build, I can add Browser Plugin to a scene.
When I then run your build it is showing a Browser in the scene, but it does not show on screen, also no properties.

https://obsproject.com/forum/resources/browser-plugin.115/

Do you have any idea how to build with Browser Plugin?

Thanks for your great work,
Maurice

**Comment by johnboiles** [comment]
Nope, I don't know anything about the browser plugin! I think I might have seen some chatter on the Discord that the browser plugin is broken on the mac or something like that.

I'm going to close this since it's not related to `obs-mac-virtualcam`, but instead is more of a general [obsproject/obs-studio](https://github.com/obsproject/obs-studio) or maybe [obsproject/obs-browser](https://github.com/obsproject/obs-browser) issue.

If you're able to build OBS locally with the browser plugin, then have reason to believe there is some bug related to this plugin, feel free to re-open.

**Comment by dodgepong** [comment]
The browser plugin is not broken on Mac. It is missing the ability to play WebRTC video, but that is the only known issue.

**Comment by johnboiles** [comment]
Thanks for the additional context @dodgepong!

**Comment by hkatzdev** [comment]
I think we should reopen this. When I build the .app trying to use browser for video source bricked the app (can't open it at all now). Log available at https://pastebin.com/FtHjhtEW

**Comment by johnboiles** [comment]
If you don't include the `obs-mac-virtualcam` plugin does the browser source work?

**Comment by hkatzdev** [comment]
I forgot to update with results - it turns out I was using the wrong browser environment variable. Once I changed it it works - the pkg I sent out a while ago confirms this.
