### ISSUE TITLE
had you considered ndi input?

### ISSUE THREAD

**Issue by technovangelist** [johnboiles/obs-mac-virtualcam#3]
This looks very cool. Had you thought of letting this run as a standalone app that receives an NDI stream? Then have OBS output to NDI and then this can be on a separate machine and push to zoom, etc.

**Comment by signalwerk** [comment]
@technovangelist This plugin is coming from a discussion over [here](https://github.com/obsproject/rfcs/pull/15#issuecomment-607986764). There were many discussions why and why not NDI. I think for the moment it's a good idea to stabilize the codebase first and bring it into OBS before broadening the scope. Do you agree with that? I would recommend to close the ticket and see if people (you?) will take it to the next level once it's ready.

**Comment by johnboiles** [comment]
I think NDI is very interesting and I'm sure a lot of the code we're developing here could be reused for NDI! But I think having this functionality integrated with OBS makes for an easier user experience. Going to close this for now, but would love to see this effort reused as an NDI tool that could do the same!

**Comment by chrisspiegl** [comment]
Hello everybody, I see this is working, but I just wondered the same thing. Interesting enough, NewTek / NDI already has a solution as well and I wondered what the difference between these two would be?

NewTek is providing the NDI Tools and at https://ndi.tv/tools/ you can also find the NDI Virtual Input. With that and the OBS NDI Plugin installed, one can also use the OBS Output as a webcam.

I get the point about being easier user experience once it is actually merged into OBS to "just work" without any stand alone apps to run in the background as well as no need for plugins to be installed.

Just some thoughts I wanted to leave here though.

**Comment by gxalpha** [comment]
This plugin is targeted to fit [the RFC](https://github.com/obsproject/rfcs/blob/master/accepted/0015-virtual-camera-support.md) which specifies that a more general approach á la NDI as it would be way out of scope, I can summarize the main reasons against it tho:
* When this project was started in march, there was no NDI cam available for Mac. They just released it a few week ago, probably due to customer pressure.
* Having to need the NDI cam run in the background is, as you said, a terrible user experience.
* When using something like the NDI cam, you rely on third parties. You do not want to rely on third parties as they need to keep up support for the system (NewTek could just decide to ditch there virtualcam for 10.16, companies are unpredictable) and may for whatever reason decide they don't want you to use there service anymore and ban it, both things would leave you with nothing.

All things considered, using NDI would be a downgrade in every scenario, I don't see any benefits compared to what this plugin does.
Anyways, this discussion has already taken place and I really don't think we need to reiterate it at the moment.
