### ISSUE TITLE
Problem compiling: QMainWindow.h not found and CMIOHardwarePlugin.h not found on case sensitive filesystems

### ISSUE THREAD

**Issue by vIceBerg** [johnboiles/obs-mac-virtualcam#32]
Hi.

I followed the instructions step by step and when compiling the plug-on, I get those two errors:

plugin-main.cpp:4:10: fatal error: 'QMainWindow.h' file not found
'CoreMediaIO/CMIOHardwarePlugin.h' file not found

My Mac uses an case-sensitive FS, and I found out that the files in the source code are miscased.

So I changed the following files:
plugin-main.cpp
#include <QMainWindow.h> TO #include <qmainwindow.h>
#include <QAction.h> TO #include <qaction.h>

CMIO_DP_SampleVCam_PlugInInterface.cpp
#include <CoreMediaIO/CMIOHardwarePlugin.h> TO #include <CoreMediaIO/CMIOHardwarePlugIn.h>

After those changes, I rebuild the project (using the command line) and it works.

I could submit a PR, but I don't know if the problem occurs only on my system. I wrote this to help others if they encounter the same issue.

**Comment by johnboiles** [comment]
Oh interesting. I asume you have a case sensitive file system on your Mac?

**Comment by vIceBerg** [comment]
Exactly. My FS is case sensitive.

**Comment by johnboiles** [comment]
I'm sure I copy pasted these imports from somewhere else in the OBS codebase.
If someone wanted to help maybe look into what is the best practice for these headers that'd be great. We need to answer:

Does QT normally name it's headers with CamelCase and something is nonstandard with @vIceBerg's QT installation? Or does QT  normally name it's headers as lowercase and the code I copy pasted only works because most macs have a case insensitive file system?

**Comment by johnboiles** [comment]
Closing this since we now have a pkg build to use instead.

**Comment by johnboiles** [comment]
Also it appears that `QMainWindow.h` is the correct naming according to the docs https://doc.qt.io/qt-5/qmainwindow.html
