### ISSUE TITLE
I don't see obs virtual camera on Google Chrome meets 

### ISSUE THREAD

**Issue by kam1092** [johnboiles/obs-mac-virtualcam#52]

**Comment by kam1092** [comment]
i  clicked on start virtual camera an i don't see the option to click on OBS virtual camera on google meets i closed an reopened my browser nothing showed up

**Comment by gxalpha** [comment]
Could you please provide further information?

**Comment by kam1092** [comment]
![Screen Shot 2020-04-27 at 1 47 18 PM](https://user-images.githubusercontent.com/23743244/80403562-c67bf480-888d-11ea-9777-54034ea175d1.png)

**Comment by kam1092** [comment]
![Screen Shot 2020-04-27 at 1 49 32 PM](https://user-images.githubusercontent.com/23743244/80403655-f0351b80-888d-11ea-8184-58498bb2d172.png)

**Comment by kam1092** [comment]
so my virtual camera is on but i don't see it in google meets

**Comment by kam1092** [comment]
that's on google chrome

**Comment by johnboiles** [comment]
Does it work in other programs like QuickTime?

**Comment by kam1092** [comment]
yes it works on QuickTime

**Comment by johnboiles** [comment]
And you're sure you completely closed Chrome (CMD-Q) and then reopened it _after_ starting the virtualcam output?

**Comment by kam1092** [comment]
i closed chrome and even restarted my computer

**Comment by johnboiles** [comment]
👍 Do you see anything in Console.app that might be relevant? Maybe search `obs-mac-virtualcam` in Console.app. If nothing comes up, then maybe paste the log when you open Chrome and try to access the virtual camera. For comparison sake also paste the log from when you open QuickTime and open the virtual camera.

**Comment by carlmes** [comment]
I don't have Chrome, but tried a couple of other browsers on https://meet.google.com

- FireFox: doesn't work. None of the my other virtual cams (such as Snap camera, CamTwist) show up either
- Safari: same as FireFox, only the built in webcam is available
- Brave: works fine
- Edge: works fine

It's probably a security issue, similar to latest Zoom app breaking third party virtual cameras due to driver signing?

**Comment by ayroblu** [comment]
Though covered in previous discussion, I use google meet as well and just wanted to share my experience. I went through a couple iterations here.
1. You must restart chrome when you turn on the virtualcam, it doesn't pick it up other wise (see snap camera who have this recommendation on their setup page) https://snapcamera.snapchat.com/guides/getting-started/
2. If you turn off virtualcam / obs, then when you come back later and want to use it again, you probably need to restart your browser again. This contrasts with zoom and applications like camtwist, epoccam which leave some kind of server process running: 
![image](https://user-images.githubusercontent.com/4915682/80861614-8343cc00-8c67-11ea-8b47-f01a9ce1b32a.png)

I'd recommend for future use, to just leave the server running, and being able to turn it off in obs, so that I don't have to restart my browser whenever I turn on obs

**Comment by gxalpha** [comment]
This is a known issue. It is going to be fixed once the new DAL plugin is implemented, though that might take some more time

**Comment by ssjunior** [comment]
Same happens here. I can use it on Hangouts, but not in Meet. Besides that the images is horizontally flipped.

Tks for the great work till now. :)

**Comment by mrichmon** [comment]
+1 on reversed video output.

**Comment by johnboiles** [comment]
Can y'all post a screenshot of OBS next to the meet window where it's reversed?

**Comment by ayroblu** [comment]
You can flip horizontally in obs. Some cameras are selfie / mirror style,
and some are normal. You can pick the style.
All websites use webrtc, so you can find a site like
https://webrtc.github.io/samples and try some out and see if they work for
you.

**Comment by gxalpha** [comment]
Regarding reversed output:
The preview on some apps will reverse the output of cameras. This is done so that if you move your hand to the left in reality, it will also move to the left on the screen. However, you shouldn't need to worry about that:
While the preview is reversed, the screen that your meeting partners see isn't. Simply make sure that you didn't flip it in OBS (Your partner will see what you see in the OBS-preview).
May need to add this to readme.

**Comment by johnboiles** [comment]
I think this is all fixed up right now. Reversed (mirrored) output is expected in the preview of most video conferencing apps.

**Comment by ssjunior** [comment]
Tks @johnboiles!
