### ISSUE TITLE
OBS build fails with  ARC error

### ISSUE THREAD

**Issue by mkarliner** [johnboiles/obs-mac-virtualcam#57]
OBS build fails thusly:

[ 99%] Built target obs
/Users/mike/Src/obs-studio/plugins/mac-syphon/syphon.m:11:35: error: ARC forbids Objective-C objects in struct
        SYPHON_CLIENT_UNIQUE_CLASS_NAME *client;
                                         ^
1 error generated.
make[2]: *** [plugins/mac-syphon/CMakeFiles/mac-syphon.dir/syphon.m.o] Error 1
make[1]: *** [plugins/mac-syphon/CMakeFiles/mac-syphon.dir/all] Error 2

**Comment by johnboiles** [comment]
Go to the OBS Discord for support for building OBS from source. That's out of the scope of this repository.

You can also try the in-progress instructions for using the nightly builds https://github.com/johnboiles/obs-mac-virtualcam/issues/23#issuecomment-623488410

**Comment by mkarliner** [comment]
Agreed, my apologies. 
Is there a channel for reporting success rather than issues? 
I've had good results with Jitsi and Ring Central

**Comment by johnboiles** [comment]
@mkarliner in generally feel free to celebrate success in the OBS Discord #plugins-and-tools channels or on Twitter :D

But in this case, make a PR to report success with Jitsi and Ring Central in the [COMPATIBILITY.md file](https://github.com/johnboiles/obs-mac-virtualcam/blob/master/COMPATIBILITY.md)

**Comment by gxalpha** [comment]
Jitsi is a web app and as such accessed through a browser, which is why we have the browsers in there. I wouldn't put web apps on the file, because the browser would the problem there, not the web app

**Comment by mkarliner** [comment]
Fair point, however...

Jitsi is also a mobile app and I've just checked the Android version +1

Mike

**Comment by gxalpha** [comment]
The mobile app has nothing to do with OBS and there is no mobile OBS version that could benefit from this plugin, the fact that there is a mobile app would make things even more confusing in my opinion

**Comment by mkarliner** [comment]
Sorry, you are quite right, serves me right for trying to
do three things at once.

Mike

**Comment by johnboiles** [comment]
There is a Jitsi Desktop app! https://desktop.jitsi.org/Main/Download

**Comment by gxalpha** [comment]
oh, really!
My mistake then.

@mkarliner have you tried the web app or the desktop version?

**Comment by mkarliner** [comment]
The Jitsi project originally started as IM (XMPP/Jabber)
and Voice (SIP). Unfortunately, the desktop app, Jitsi Desktopm, supports
those, not Jitsi Meet, which is the Video Conf.

Long and short of it is, as you rightly say, Jitsi Meet is a
web app and should not strictly be listed as compatible,
although  I personally don't think it would hurt.

Mike

**Comment by johnboiles** [comment]
Got it thanks for the context. I don't have a strong feeling either way about whether to include specific web apps in the compatibility list. If we did include them maybe we do it in a parentheses by the browser line item to mark what we've confirmed to work, or maybe as a separate section. Ideally we don't clutter up the primary table with several entries for each web app (e.g. 'Jitsi Meet (Chrome)', 'Jitsi Meet (Firefox)', etc) since that would make the list way too noisy.

My main question is whether it's possible for the virtual camera to work in one web app but not another in the same browser. I think the answer is no, but if I'm wrong we should def give more space to capturing this in the compatibility list.
